





name: Terraform Deployment

# This will run every time we create push a commit to "main" branch.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows

on:
  push:
    branches:
      - dev

jobs:
  CICD-CREATE-ECS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve
        env:
            TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }} # terraform apply -var="account_id=255945442255"
            TF_VAR_region: ${{ secrets.AWS_REGION }}
            TF_VAR_ecr_repo: ${{ secrets.ECR_REPOSITORY }}
            TF_VAR_image_tag: ${{ github.sha }}
